CoreBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: CoreBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
