<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOympkrg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOympkrg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOympkrg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOympkrg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOympkrg\appProdProjectContainer(array(
    'container.build_hash' => 'Oympkrg',
    'container.build_id' => 'edee5e67',
    'container.build_time' => 1542884244,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOympkrg');
