app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix:   /product
    
app_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /category