<?php

namespace CoreBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository {

    public function getByName() {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p, c')
                ->where('p.name like ?1')
//                ->where($qb->expr()->andX(
//                    $qb->expr()->like('p.name', '?1')  
//                ))
                ->andWhere('p.qte > :qte')
                ->setParameter(1, '%' . "product 1" . '%')
                ->setParameter('qte', 1)
                ->leftJoin('p.categorie', 'c');

        return $qb->getQuery()->getResult();
    }
    
    public function getProductsByCategory($cat){
        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
                ->leftJoin('p.categorie', 'c')
                ->where('c.name = ?1')
                ->setParameter(1, $cat);
        
        return $qb->getQuery()->getResult();
    }
    
    public function getProductsByCategoryArray($cat){
        $qb = $this->createQueryBuilder('p');
        $qb->select('p, c')
                ->leftJoin('p.categorie', 'c')
                ->where('c.name = ?1')
                ->setParameter(1, $cat);
        
        return $qb->getQuery()->getArrayResult();
    }
    
    public function findAllArray(){
        $qb = $this->createQueryBuilder('p');
        $qb->select('p, c')
                ->leftJoin('p.categorie', 'c');
        
        return $qb->getQuery()->getArrayResult();
    }

}
